FROM golang:1.21 AS builder

WORKDIR /src/ 

## go source copy
COPY . . 

RUN go build -o /app/main.go main.go

## add so 
FROM fedora:40 

EXPOSE 3000:3000 

WORKDIR /app
COPY --from=builder /app/main.go ./

CMD ["./main.go"]

