FROM node:lts AS builder

WORKDIR /app 
COPY webui webui

WORKDIR /app/webui
# vite build target production
RUN npm install && npm run build

FROM nginx:stable 

COPY --from=builder /app/webui/dist /usr/share/nginx/html